from .booking_management import booking_management_router
from .booking_management import bookings_list_router

from .cmd_admin import router as command_admin_router

from .computer_management import add_computer_router
from .computer_management import computer_list_by_category_router
from .computer_management import computer_list_router
from .computer_management import computer_management_router
from .computer_management import delete_computer_router

from .payment_management import payment_management_router
from .payment_management import user_payment_history_router

from .ticket_management import close_ticket_router
from .ticket_management import get_ticket_by_id_router
from .ticket_management import open_tickets_router
from .ticket_management import ticket_management_router

from .user_management import block_user_router
from .user_management import change_balance_router
from .user_management import get_user_by_id_router
from .user_management import unblock_user_router
from .user_management import user_booking_history_router
from .user_management import user_list_router
from .user_management import user_management_router
