"""Refactoring of database models

Revision ID: a6ded8aef145
Revises: 148a44e076ba
Create Date: 2023-10-29 16:33:42.334903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ded8aef145'
down_revision: Union[str, None] = '148a44e076ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('bookings', 'computer_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'computer_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
