"""Computers: Added price per hour

Revision ID: bc5216661481
Revises: bf240819a555
Create Date: 2023-11-02 09:42:29.485085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5216661481'
down_revision: Union[str, None] = 'bf240819a555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('price_per_hour', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computers', 'price_per_hour')
    # ### end Alembic commands ###
