"""Added new columns to the users table

Revision ID: bf240819a555
Revises: a6ded8aef145
Create Date: 2023-10-29 19:50:56.761827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bf240819a555'
down_revision: Union[str, None] = 'a6ded8aef145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, default=False))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=False, default=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, default=True))
    op.add_column('users',
                  sa.Column('balance', sa.Integer(), sa.CheckConstraint("balance >= 0"), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'email_address')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
